### ISSUE TITLE
Theme removes background on restart

### ISSUE THREAD

**Issue by lifebarier** [jonathanlermitage/intellij-darcula-sombre-theme#1] opened 2019-05-03 05:58 UTC
It seems that every time I restart intellij with this theme selected it removes background that was set (ctrl+shift+a - set background image). Does not happen with standard Dracula theme. Intellij ultimate 19.1.1

**Comment by jonathanlermitage** [comment] 2019-05-03 12:21
Thx for reporting this issue. I'll look at this asap.

**Comment by jonathanlermitage** [comment] 2019-05-03 14:06
It seems to be a bug in IntelliJ. I faced the same issue with:
* an other custom theme (Dark purple)
* a new theme that customize nothing

**Comment by jonathanlermitage** [comment] 2019-05-03 14:06
Confirmed: https://youtrack.jetbrains.com/issue/IDEA-211541

It seems to be fixed in 2019.1.2

**Comment by jonathanlermitage** [comment] 2019-05-03 14:20
Fix confirmed, it works fine with IJ 2019.1.2 RC

**Closed as completed by jonathanlermitage** 2019-05-03 14:20 UTC
Labels: bug
